//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSPModelLibrary {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class PathSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PathSettings defaultInstance = ((PathSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PathSettings())));
        
        public static PathSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B:\\Games\\steamapps\\common\\Kerbal Space Program\\GameData")]
        public string GameDataPath {
            get {
                return ((string)(this["GameDataPath"]));
            }
            set {
                this["GameDataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalPartDirs {
            get {
                return ((string)(this["AdditionalPartDirs"]));
            }
            set {
                this["AdditionalPartDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Squad\\Parts")]
        public string VanillaDir {
            get {
                return ((string)(this["VanillaDir"]));
            }
            set {
                this["VanillaDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\SquadExpansion\\MakingHistory\\Parts,\\SquadExpansion\\Serenity\\Parts")]
        public string DLCDirs {
            get {
                return ((string)(this["DLCDirs"]));
            }
            set {
                this["DLCDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\PlanetaryBaseInc\\BaseSystem\\Parts,\\PlanetaryBaseInc\\ContainerSystem,\\SCANsat\\Par" +
            "ts,\\TarsierSpaceTech\\Parts")]
        public string ModDirs {
            get {
                return ((string)(this["ModDirs"]));
            }
            set {
                this["ModDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcludedDirs {
            get {
                return ((string)(this["ExcludedDirs"]));
            }
            set {
                this["ExcludedDirs"] = value;
            }
        }
    }
}
